#!/bin/bash

# ADSL


while :
do
clear
echo "----------------------------------"
echo          "Main Menu"
echo "----------------------------------"
echo "[1] Connect to Internet"
echo "[2] Disconnect from Internet"
echo "[3] Show me ip"
echo "[4] Checking the connection"
echo "[5] Exit"
echo "----------------------------------"
echo -n "Enter your menu choice [1-5]: "

read i
case $i in
1) sudo ppp -ddial pppoe; echo Press Enter Key...; read;;
2) sudo kill -9 `cat /var/run/tun0.pid `; echo "Connection is terminated"; echo Press Enter Key...; read;;
3) /sbin/ifconfig tun0 | awk '/netmask/{print $2}'; echo Press Enter Key; read;;
4) ping -c 4 google.com ; echo Press Enter Key; read ;;
5) exit 0;;
*) echo "Type digits from 1 to 5"; echo Press Enter Key; read;;

esac
done



#dhcpd obsd



if [ `ps -auxc | awk ' /_dhcp/ { print $11 }'` 2> /dev/null = "dhcpd" ]
	then
		kill -9 `ps -aux | awk ' /_dhcp/ { print $2 }'` 2> /dev/null
		dhcpd
		echo "Dhcpd has been restarted
	else
		echo "Dhcpd disabled
